# Generated by Django 2.1.7 on 2019-04-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20190329_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='carts.Cart'),
            preserve_default=False,
        ),
    ]
