# Generated by Django 2.1.7 on 2019-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productwithimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='photoframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=299.99, max_digits=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='products/img/')),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shipdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productwithimage',
            name='image',
            field=models.ImageField(upload_to='products/img/'),
        ),
    ]
