# Generated by Django 2.1.7 on 2019-03-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190325_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwithimage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productwithimage',
            unique_together={('title', 'slug')},
        ),
    ]
