# Generated by Django 2.1.7 on 2019-03-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwithimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
    ]
