# Generated by Django 2.1.7 on 2019-03-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190330_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwithimage',
            name='category',
        ),
    ]
