# Generated by Django 2.1.7 on 2019-03-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productwithimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwithimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.Category'),
            preserve_default=False,
        ),
    ]
