# Generated by Django 2.1.7 on 2019-03-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190331_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productwithimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
