# Generated by Django 2.1.7 on 2019-03-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productwithimage_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('title', 'slug')},
        ),
    ]
